- name: Get API versions from FlashArray
  hosts: localhost
  gather_facts: no
  vars:
    arrayurl: 172.17.65.140
 
  tasks:
    - name: api version
      uri:
        url: https://{{ arrayurl }}/api/api_version
        method: GET
        validate_certs: no
        return_content: yes
      register: api_version
 
    - name: show supported versions
      debug: msg="{{ api_version.json }}"
